[target_servers]
192.168.64.19 ansible_user=abaranov ansible_password=123456 ansible_become_password=123456

[target_servers:vars]
created_user=devuser
public_key_path=files/devuser_key.pub
workdir_path=/opt/devuser_workdir
